import type { Metadata } from "next";
import { Open_Sans, Cormorant } from "next/font/google";
import "./globals.css";

const open_sans = Open_Sans({
  subsets: ["latin"],
});

const cor = Cormorant({
  subsets: ["latin"],
  variable: "--font-cormorant",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${open_sans.className} ${cor.variable} antialiased bg-black h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
